(window as any).translations = Object.assign((window as any).translations || {}, {
    DESCRIPTION_WORKFLOWSTEPSIMPLE: 'Base step',
    DESCRIPTION_WORKFLOWSTEPCOMPOUND: 'Set of multiple steps',
    DESCRIPTION_STEP_RUN_TYPE_SEQUENTIAL: 'Workflow will wait for the step to complete',
    DESCRIPTION_STEP_RUN_TYPE_PARALLEL: 'Workflow will not wait for this step to complete',
    DESCRIPTION_STEP_RUN_TYPE_SERVICE: 'Workflow will wait for this step to be healthy',
    NAME_WORKFLOWSTEPSIMPLE: 'Simple step',
    NAME_WORKFLOWSTEPCOMPOUND: 'Compound step',
    NAME_STEP_RUN_TYPE_SEQUENTIAL: 'Sequential Step',
    NAME_STEP_RUN_TYPE_PARALLEL: 'Parallel Step',
    NAME_STEP_RUN_TYPE_SERVICE: 'Service Step',
    SOURCE_CATALOG: 'Use official Docker image',
    SOURCE_MANUAL: 'Use custom Docker image',
    SOURCE_STEP: 'Use image generated by a previous step'
});
